### PR TITLE
Initial BOMs for Light Platform

### PR DESCRIPTION
**Pull request by jawaff**
The BOM files are based on POM files defined in the light-4j and light-rest-4j repositories. They probably aren't perfect, but they should integrate nicely with light-4j and light-rest-4j at the least.

One possible problem that I'm not sure about is the fact that light-4j has a dependency on jose4j and undertow. I don't know if that is a necessary dependency for the base light-platform-bom. I would have guessed that undertow and jose4j are only needed for the light-rest-4j projects.

Another thing, I made these BOM files for version 2.0.8-SNAPSHOT of the Light platform. I might need to make another commit to fully conform to the build system and we can add more BOM variations if necessary as well.

### CODE REVIEW

**Comment by jawaff** [comment]
I'm trying to figure out a reasonable way to test the BOM files so that they can be published with confidence. I don't think it's possible to validate that the correct dependencies are listed, but it is possible to fail builds when conflicting versions are present (multiple versions for a single artifact).

**Comment by jawaff** [comment]
@stevehu If you know anyone else that could be a good reviewer, then let me know.

**Comment by jawaff** [comment]
These BOM files are a bit different than how Spring and Jersey uses them. Spring and Jersey define only a couple of multi-module projects. They define 3rd party dependencies in a parent pom file within those projects (which is essentially their 3rd party BOM). In addition their BOM files are defined within their multi-module projects and are only used to list the modules of the project in a dependency management section. These BOM files are strictly used by users of the spring/jersey projects.

I at first thought that the Light platform's repositories were setup differently, but I'm not sure if my first observation was correct. After wasting my time making the wrong type of BOM files I've figured out what I should have done from the beginning. My company's odd repository setup gave me a bad understanding of how Maven projects should be setup. I learned something from this though and it was totally worth it.

**Comment by stevehu** [comment]
@jawaff The undertow and Jose4j are hard dependencies for light-4j and all other frameworks. Undertow is the core HTTP server and Jose4j is used to handle the security with JWT.

**Pull request closed without merging**
